version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - COINGECKO_API_KEY=${COINGECKO_API_KEY}
      - COINMARKETCAP_API_KEY=${COINMARKETCAP_API_KEY}
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET}
      - ETH_RPC_URL=${ETH_RPC_URL}
      - POLYGON_RPC_URL=${POLYGON_RPC_URL}
      - BASE_RPCURL=${BASE_RPCURL}
      - BASE_SEPOLIA_RPCURL=${BASE_SEPOLIA_RPCURL}
      - INDEX_REGISTRY_ADDRESS=${INDEX_REGISTRY_ADDRESS}
      - PSYMM_ADDRESS=${PSYMM_ADDRESS}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - USDC_ADDRESS_IN_BASE=${USDC_ADDRESS_IN_BASE}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis # Only depends on Redis now
    volumes:
      - .:/app
      - /app/node_modules

  redis:
    image: redis:7
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  redis-data:
